version: 0.1

phases:
  build:
    commands:
      - npm install
      - num run webpack

artifacts:
  files:
    - index.html
    - babel.html
    - favicon.ico
    - styles/main.css
    - images/*
    - dist/bundle.js
